runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  login: required

- url: /css
  static_dir: css

- url: /javascript
  static_dir: javascript

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
