runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  login: required

- url: resources/css
  static_dir: /resources/css/

- url: resources/scripts
  static_dir: /resources/scripts/

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
